DjangoYoutube/urls.py
# from django.urls import include, path
# from django.contrib import admin
#
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     # path('music/', music.site.urls)
#     # path('music/', include('music.urls')),
# ]

from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns
from companies import views

urlpatterns = [
    url(r'^$',views.HomeView.as_view()), # main page / was empty as was working
    url(r'^admin/', admin.site.urls),
    # path('', include('music.urls')),    # if empty space then do...
    url(r'^music/', include('music.urls')),
    url(r'^stocks/', views.StockList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
# create urls just for this music section
#
from django.conf.urls import url
# from django.urls import path, url
from . import views                         # import from this folder

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /music/712/
    # /music/<album_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # /music/album=2/update
    url(r'album=(?P<pk>[0-9]+)/update$', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/2/delete/
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    # # /music/<album>/favorite/
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),

    # /music/album/<album>/song/add/
    url(r'album/(?P<pk>[0-9]+)/song/add$', views.SongCreate.as_view(), name='song-add'),

    # /music/album/<album>/song/2/update
    url(r'album/(?P<pk>[0-9]+)/update/$', views.SongUpdate.as_view(), name='song-update'),

    # /music/album/song/2/delete/
    url(r'album/song/(?P<pk>[0-9]+)/delete/$', views.SongDelete.as_view(), name='song-delete'),
]

companies/models.py
from django.db import models


class Stock(models.Model):
    ticker = models.CharField(max_length=10)                               # facebook is fb , yahoo is yhoo
    open = models.FloatField()
    close = models.FloatField()
    volume = models.IntegerField()

    def __str__(self):      # we want to have a string representation of this
        return self.ticker

music/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
### Red album primary key is 1
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    # album_logo = models.FileField()
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)      # the foreignkey is gonna be 1
                                                                    # if delete album delete all the songs conn to it.
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        # album = models.ForeignKey(Album, on_delete=models.CASCADE)
        # return reverse('music:detail', kwargs={'pk': self.pk})
        return reverse('music:index')
        # album = models.ForeignKey(Album)
        # return reverse('music:detail', kwargs=album.id)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

companies/views.py
from django.shortcuts import render

from django.shortcuts import get_object_or_404
from rest_framework.views import APIView          # make these normal views return API data
from rest_framework.response import Response      # we can send a specific response status
from rest_framework import status
from .models import Stock
from.serializers import StockSerializer

# Create your views here.

# List all stocks or create a new one
# stocks/FB/ or /AMZN/
class StockList(APIView):

    def get(self, request):     # reading information
        stocks = Stock.objects.all()
        serializer = StockSerializer(stocks, many=True)
        return Response(serializer.data)

    def post(self):    # submitting the form
        pass

from django.views import generic
from music.models import Album

class HomeView(generic.ListView):
    template_name = 'music/home.html'
    context_objext_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views import View
from .models import Album
from .forms import UserForm
from django.http import HttpResponseRedirect


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return  render(request, self.template_name, {'form': form})

    # process form data (when user adds some data)
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    # request.user  if you want to get the info about a user. don't write this later.
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})


# JUST DELETE IT IF FAVORITE IN INDEX MAIN MAGE DOESN'T WORK

from django.shortcuts import get_object_or_404
from .models import Song

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album': album,
            'error_message': "You did not select a valid song",
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

    # else:                                                                 # can be made as a cycle Favorite -> Unfavorite
    #     if selected_song.is_favorite == False:
    #         selected_song.is_favorite = True
    #         selected_song.save()
    #     else:
    #         selected_song.is_favorite = False
    #         selected_song.save()
    #     return render(request, 'music/detail.html', {'album': album})






class SongCreate(CreateView):
    model = Song
    fields = ['album', 'file_type', 'song_title', 'is_favorite']

class SongUpdate(UpdateView):
    model = Song
    fields = ['album', 'file_type', 'song_title', 'is_favorite']

class SongDelete(DeleteView):
    model = Song
    success_url = reverse_lazy('music:index')

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% load static %}

{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
<!--                    <h3>Add a New Album</h3> -->

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>



                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

music/templates/music/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Maberr{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <script scr="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script scr="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Maberr</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/form-template.html
{% load static %}

{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/home.html
<!-- Loads the path to your static files -->
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Maberr{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <script scr="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script scr="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Maberr</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>




{% block body %}

    <br><br><br><br><br><br>
    <h1><!-- some text -->
        <li class="active">
            <a href="{% url 'music:index' %}"><p style="text-align:center;">Welcome!
                <p style="text-align:center;"><font size="+4"><span class="glyphicon glyphicon-th-large" aria-hidden="true"><!-- some text --></span> </font></p>
                <p style="text-align:center"> <img src="https://cdn.shopify.com/s/files/1/1195/8136/t/5/assets/welcome-logo.svg?v=11540035806959164021" width="170" height="85"></p>
            </a>
        </li>
    </h1>




{% endblock %}

music/templates/music/index.html
<!-- Loads the path to your static files -->

{% extends 'music/base.html' %}


{% block body %}
    {% if all_albums %}
        <h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bang! Check out my Albums:</h3>
        <ul>

            {% for album in all_albums %}

                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">

                        <!-- Album logo -->
                        <a href="{% url 'music:detail' album.id %}">
                            <!-- <img src="{{ album.album_logo.url }}" class="img-responsive">  --> <!-- it goes for models.FileField -->
                            <img src="{{ album.album_logo }}" class="img-responsive">
                        </a>

                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm">View Details</a>


                            <!-- Update -->
                            <a href="{% url 'music:album-update' album.id%}" class="btn btn-primary btn-sm">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-repeat" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                  <path fill-rule="evenodd" d="M2.854 7.146a.5.5 0 0 0-.708 0l-2 2a.5.5 0 1 0 .708.708L2.5 8.207l1.646 1.647a.5.5 0 0 0 .708-.708l-2-2zm13-1a.5.5 0 0 0-.708 0L13.5 7.793l-1.646-1.647a.5.5 0 0 0-.708.708l2 2a.5.5 0 0 0 .708 0l2-2a.5.5 0 0 0 0-.708z"/>
                                  <path fill-rule="evenodd" d="M8 3a4.995 4.995 0 0 0-4.192 2.273.5.5 0 0 1-.837-.546A6 6 0 0 1 14 8a.5.5 0 0 1-1.001 0 5 5 0 0 0-5-5zM2.5 7.5A.5.5 0 0 1 3 8a5 5 0 0 0 9.192 2.727.5.5 0 1 1 .837.546A6 6 0 0 1 2 8a.5.5 0 0 1 .501-.5z"/>
                                </svg>
                            </a>

                            <!-- Delete -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}"/>
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>




                            <!-- Favorite -->
                            <!--<a href="#" class="btn btn-default btn-sm btn-favorite"> -->
                                <!--<span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>-->
                            <!--</a>-->
                            <!--<br/>-->

                            <!--
                            <img src="{{ album.album_logo.url }}" style="width: 300px;">
                            <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
                            -->
                        </div>

                    </div>
                </div>

            {% endfor %}
        </ul>
    {% else %}
        <h3>You don't have any albums...</h3>>
    {% endif %}
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% load static %}

{% block title %}Register{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Create a New Account</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>



                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

music/templates/music/song_form.html
{% extends 'music/base.html' %}
{% load static %}

{% block title %}Add a New Song{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
   <!--                 <h3>Add a New Song</h3> -->

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>



                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}